### ISSUE TITLE
Overdue tasks not resetting?

### ISSUE THREAD

**Issue by akeslo** [amitness/habitist#1]
Is this still working as designed?  I have an overdue habit which is not getting rescheduled for today.  After some debugging, the following query yields no tasks even though I have an overdue task pending:
tasks = user.search_tasks(todoist.Query.OVERDUE)

**Comment by akeslo** [comment]
Messy workaround:

```
#Check for Overdue
    tasks = user.get_tasks()
    for task in tasks:
        
        content = task.content     
        habit = is_habit(content)      
        if habit:
            due = datetime.strptime(task.due_date_utc, '%a %d %b %Y %H:%M:%S %z').replace(tzinfo=None)
            complete = task.checked
            
            if today > due and complete == 0:
                task.date_string = 'ev day starting tod'
                update_streak(task, 0)
            
```

**Comment by amitness** [comment]
Yes, the todoist Query API has just been deprecated this week. I've updated the script with working version.

**Comment by akeslo** [comment]
Works well! Thanks!
