### ISSUE TITLE
Activating Forked Workflow

### ISSUE THREAD

**Issue by JoelRSimpson** [amitness/habitist#16]
I was new to github workflows and found that the workflow was disabled due to coming pre-configured from a forked repository.  It would be helpful to have a step to go to Actions and activate the workflow.

**Comment by JoelRSimpson** [comment]
I'm still not able to get the workflow triggering for some reason.  I'm currently trying to build a new workflow with the same contents to see if that works.

**Comment by amitness** [comment]
@JoelRSimpson Did it work for you? It seems GitHub has a bug on their end in the actions workflow for forks. If you delete the current workflow and then again recreate it by pasting the same code, it seems to work.

**Comment by JoelRSimpson** [comment]
Yes, it looks like that worked.  I created a new workflow and copied the exact code from the existing workflow and it started working the next evening.  Thanks!
