### ISSUE TITLE
Common misconception, Seinfeld is not the creator

### ISSUE THREAD

**Issue by ernesgonzalez33** [amitness/habitist#17]
No one knows how this method came to exist, but Seinfeld himself said that it was not his idea:

https://www.reddit.com/r/IAmA/comments/1ujvrg/jerry_seinfeld_here_i_will_give_you_an_answer/ceiugt5?utm_source=share&utm_medium=web2x

So if you want, you can update that in the README

**Comment by amitness** [comment]
@ernesgonzalez33 Lol. 

Thanks for the link. I will update the README.
