### ISSUE TITLE
Workflow will not trigger

### ISSUE THREAD

**Issue by akeslo** [amitness/habitist#22]
Hi - This had worked perfectly for the longest time, all of a sudden I cannot get the workflow to trigger.  I have done the following without luck (what am I doing wrong?)

1. Delete my fork and re-forked this repo
2. Updated API Key
3. Enabled Workflow
4. Deleted Workflow and Recreated
5. Renamed master branch to main

Thanks!

**Comment by amitness** [comment]
@akeslo That's weird. It's been working perfectly for me. 

What error do you get? Do the tasks not increment by 1?

**Comment by akeslo** [comment]
@amitness I originally was not seeing the workflow as scheduled within the actions tab on github but now all of a sudden I am, I'm not sure why there was a delay.  Now everything appears to be working perfectly, I'm just waiting for another test run to run.   How long after the cron runs should the task show up in the workflow section of github?

Thanks so much for maintaining this repo, its a huge asset! 

![image](https://user-images.githubusercontent.com/3003773/105425118-bd4e6700-5c16-11eb-838d-2e8ca3aa6418.png)

**Comment by amitness** [comment]
@akeslo Did it work?

**Comment by akeslo** [comment]
> @akeslo Did it work?

Yes good to go! Thanks
