### ISSUE TITLE
does it still works with todoist?

### ISSUE THREAD

**Issue by saikatm** [amitness/habitist#23]
does it still working with todoist? it is been 3years I used it I want to use it again for tracking my habits with todoist!! please let me know if is stable and working? do I still need to use heroku for this??

**Comment by amitness** [comment]
@saikatm Nope. I've switched it from heroku to github actions. You don't need to setup heroku now.

Please read the new steps in the `README.md` file.

**Comment by saikatm** [comment]
just did it! thanks alot for maintaining the repo.

**Comment by saikatm** [comment]
Q: can I set the fork repo on my account to private?

**Comment by amitness** [comment]
@saikatm Should work regardless of whether repo is public or private. Does github allow setting forks to private?

**Comment by amitness** [comment]
Hi @saikatm. Closing this. Please feel free to re-open if there are any issues.
