### ISSUE TITLE
habitist will be disabled soon

### ISSUE THREAD

**Issue by saikatm** [amitness/habitist#25]
Ithe repo actions get disabled after somedays of working, and I am getting this emails, I do not know how to fix this please help...

> Scheduled workflows are disabled automatically after 60 days of repository inactivity. | GitHub Actions scheduled

**Comment by amitness** [comment]
@saikatm Can you try going to Actions tab on your repo? There should be an enable workflow button somewhere.

**Comment by amitness** [comment]
@saikatm Closing this. Please follow the comment above and it should work.
