### ISSUE TITLE
Increments instead of resetting

### ISSUE THREAD

**Issue by akeslo** [amitness/habitist#3]
There seems to be a bug with the current code where instead of resetting overdue habbits to 0 and setting due for the day, the habbit is incremented by 1 and kept in an overdue state.

**Comment by akeslo** [comment]
@amitness this appears to be a utc time issue from what I can tell.  When the script triggers at 12am, the due date of the overdue task and the today date end up being the same so it increments insteas of resets.  Same thing happens to the is_due function. 

Moving the today date to tomorrow  and the yesterday date to today appears to resolve the issue (still testing).

**Comment by amitness** [comment]
@akeslo Is your fix working? Have you tested it?

**Comment by briankaemingk** [comment]
I have tested it and it’s working for me!

**Comment by amitness** [comment]
@briankaemingk Thanks. I've integrated his fix.
